version: '3'
services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 12306:12306
    working_dir: /app
    volumes:
      - .:/app
    environment:
      TZ: Asia/Shanghai